spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/768001076/springcloudconfig
          search-paths: respo
          username: 768001076
          password: sj953923
      label: master
server:
  port: 1170
